### ISSUE TITLE
twitchAPI Didn't recieve pong in time, restarting doesn't restart, and crashes the program.

### ISSUE THREAD

**Issue by mmattbtw** [Teekeks/pyTwitchAPI#93]
From the people using my script, they sometimes recieve the `twitchAPI.pubsub - did not receive pong in time, reconnecting...` error, however it seems like that pubsub doesn't reconnect/the script crashes.

Is this a Twitch issue, or a pyTwitchAPI issue?

**Comment by Teekeks** [comment]
I am pretty sure that this will be fixed with the next update but just to be sure: can you post some code so that I can try to replicate this?

**Comment by Teekeks** [comment]
I just realized that your requests are not async but blocking. That might be the problem right there.

Now this is something I should fix in my library since I am currently executing callbacks not in the thread the original subscription was made from but in the thread that is used by the library client.
But since a change like that might have bigger implications on other peoples existing code who might expect that its working the way it is now, this change would have to wait for a bigger release in the future.

The good thing is that httpx does support async requests which should fix your problem (see here: https://www.python-httpx.org/async/).

I hope this might help.

**Comment by Teekeks** [comment]
@mmattbtw any update on this?

**Comment by mmattbtw** [comment]
I haven't gotten any reports of this happening so.
